In [1]:
import numpy as np
arr=np.array([1,2.0,3.0,4.0,5.0])
arr
#print(type(arr[2]))

array([1., 2., 3., 4., 5.])

In [2]:
arr=np.array([1,2,3,45,6.0,8+5j])
arr

array([ 1.+0.j,  2.+0.j,  3.+0.j, 45.+0.j,  6.+0.j,  8.+5.j])

In [3]:
arr=np.array([[1,2,3],[4,5,6],[7,5,6]])
arr.ndim

2

In [4]:
arr=np.array((1,2,3,4,5))
arr.ndim

1

In [5]:
arr1=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])  #3-D array
arr1.ndim

3

In [6]:
arr=np.array([1,2,3,4,5,6,7,8,9])
a=arr.reshape(3,3)
a.ndim

2

In [7]:
arr2 = np.array([[2,3,4],[6,7,9],[5,6,2]])
arr2[-2,-1]


9

In [8]:
arr = np.array([[[2,3,4],[6,7,9],[5,6,2]],[[41,52,32],[62,72,92],[25,26,22]]])
#arr[1,1,2]
arr[-1,-2,-1]

92

In [9]:
arr2 = np.array([[2,3,4],[6,7,9],[5,6,2]],ndmin=1)
print(arr2)
print(arr2.ndim)

[[2 3 4]
 [6 7 9]
 [5 6 2]]
2


In [10]:
arr3 = np.array([2,3,4,5,6,7,8,9,10,11,12,1])
new_arr3 = arr3.reshape(1,3,4)
print(new_arr3)
new_arr3.ndim

[[[ 2  3  4  5]
  [ 6  7  8  9]
  [10 11 12  1]]]


3

In [11]:
arr3=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new_arr=arr3.reshape(1,4,3)
print(new_arr)
new_arr.ndim

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]


3

In [71]:
#slicing for 1d array.
a=np.arange(1,11)
a[3:5]

array([4, 5])

In [69]:
#slicing for 2d array.

a=np.arange(1,13)
b=a.reshape(3,4)
print(b)
b[1:,1:3]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([[ 6,  7],
       [10, 11]])

In [86]:
#slicing for 3d array 
a=np.arange(1,28)
b=a.reshape(3,3,3)
print(b)
b[:2,1:,1:]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


array([[[ 5,  6],
        [ 8,  9]],

       [[14, 15],
        [17, 18]]])

In [95]:
#zeros.
a=np.zeros([6])
a

array([0., 0., 0., 0., 0., 0.])