In [28]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,recall_score,confusion_matrix,f1_score,precision_score,classification_report

# Using logistic regression.

In [42]:
ar=pd.read_csv(r'C:\Users\User\Downloads\Invistico_Airline.csv')

In [43]:
ar.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 129880 entries, 0 to 129879
Data columns (total 23 columns):
 #   Column                             Non-Null Count   Dtype  
---  ------                             --------------   -----  
 0   satisfaction                       129880 non-null  object 
 1   Gender                             129880 non-null  object 
 2   Customer Type                      129880 non-null  object 
 3   Age                                129880 non-null  int64  
 4   Type of Travel                     129880 non-null  object 
 5   Class                              129880 non-null  object 
 6   Flight Distance                    129880 non-null  int64  
 7   Seat comfort                       129880 non-null  int64  
 8   Departure/Arrival time convenient  129880 non-null  int64  
 9   Food and drink                     129880 non-null  int64  
 10  Gate location                      129880 non-null  int64  
 11  Inflight wifi service              1298

In [41]:
ar['Customer Type'].unique()

array(['Loyal Customer', 'disloyal Customer'], dtype=object)

In [44]:
ar['satisfaction'].unique()

array(['satisfied', 'dissatisfied'], dtype=object)

In [46]:
ar['Gender'].unique()

array(['Female', 'Male'], dtype=object)

In [48]:
ar['Type of Travel'].unique()

array(['Personal Travel', 'Business travel'], dtype=object)

In [49]:
ar['Class'].unique()

array(['Eco', 'Business', 'Eco Plus'], dtype=object)

In [57]:
customer_type=pd.get_dummies(ar['Customer Type'],drop_first=True)
satisfaction=pd.get_dummies(ar['satisfaction'],drop_first=True)
Gender=pd.get_dummies(ar['Gender'],drop_first=True)
Type_of_Travel=pd.get_dummies(ar['Type of Travel'],drop_first=True)

In [64]:
ar1=pd.concat([ar,customer_type,satisfaction,Gender,Type_of_Travel],axis=1)

In [65]:
ar1.drop(['satisfaction','Gender','Customer Type','Type of Travel'],axis=1,inplace=True)

In [68]:
ar1['Class'].replace({'Business':1,'Eco':3,'Eco Plus':2},inplace=True)

In [72]:
ar1['Arrival Delay in Minutes'].fillna(ar1['Arrival Delay in Minutes'].median(),inplace=True)

In [74]:
ar1

Age  Class  Flight Distance  Seat comfort  \
0        65      3              265             0   
1        47      1             2464             0   
2        15      3             2138             0   
3        60      3              623             0   
4        70      3              354             0   
...     ...    ...              ...           ...   
129875   29      3             1731             5   
129876   63      1             2087             2   
129877   69      3             2320             3   
129878   66      3             2450             3   
129879   38      3             4307             3   

        Departure/Arrival time convenient  Food and drink  Gate location  \
0                                       0               0              2   
1                                       0               0              3   
2                                       0               0              3   
3                                       0               0              3   
4                                       0               0              3   
...                                   ...             ...            ...   
129875                                  5               5              3   
129876                                  3               2              4   
129877                                  0               3              3   
129878                                  2               3              2   
129879                                  4               3              3   

        Inflight wifi service  Inflight entertainment  Online support  ...  \
0                           2                       4               2  ...   
1                           0                       2               2  ...   
2                           2                       0               2  ...   
3                           3                       4               3  ...   
4                           4                       3               4  ...   
...                       ...                     ...             ...  ...   
129875                      2                       5               2  ...   
129876                      2                       1               1  ...   
129877                      3                       2               2  ...   
129878                      3                       2               2  ...   
129879                      3                       3               3  ...   

        Baggage handling  Checkin service  Cleanliness  Online boarding  \
0                      3                5            3                2   
1                      4                2            3                2   
2                      4                4            4                2   
3                      1                4            1                3   
4                      2                4            2                5   
...                  ...              ...          ...              ...   
129875                 4                4            4                2   
129876                 3                1            2                1   
129877                 4                2            3                2   
129878                 3                2            1                2   
129879                 5                3            3                3   

        Departure Delay in Minutes  Arrival Delay in Minutes  \
0                                0                       0.0   
1                              310                     305.0   
2                                0                       0.0   
3                                0                       0.0   
4                                0                       0.0   
...                            ...                       ...   
129875                           0                       0.0   
129876                         174                     172.0   
129877                         155          

In [76]:
x=ar1.drop('satisfied',axis=1)
y=ar1[['satisfied']]

In [77]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [79]:
logistic_model=LogisticRegression()
logistic_model.fit(x_train,y_train)

c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [81]:
y_pred=logistic_model.predict(x_test)
y_pred_train=logistic_model.predict(x_train)

In [82]:
y_pred[10:15]

array([0, 1, 1, 0, 1], dtype=uint8)

In [84]:
y_test[10:15]

satisfied
63350           1
2776            1
122540          1
41299           0
120796          1

In [85]:
confusion_matrix(y_train,y_pred_train)

array([[34851, 12138],
       [ 8593, 48322]], dtype=int64)

In [86]:
confusion_matrix(y_test,y_pred)

array([[ 8824,  2980],
       [ 2034, 12138]], dtype=int64)

In [87]:
cls_report=classification_report(y_test,y_pred)
print(cls_report)

              precision    recall  f1-score   support

           0       0.81      0.75      0.78     11804
           1       0.80      0.86      0.83     14172

    accuracy                           0.81     25976
   macro avg       0.81      0.80      0.80     25976
weighted avg       0.81      0.81      0.81     25976



In [88]:
acc_score=accuracy_score(y_test,y_pred)
print(acc_score)

0.8069756698490914


In [89]:
acc_score_train=accuracy_score(y_train,y_pred_train)
print(acc_score_train)

0.8004792885740684
